"""Add service relationship tracking columns to conversation_contexts

Revision ID: 0d4ae3668d01
Revises: 78b6df983ffe
Create Date: 2025-11-09 00:16:40.240961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d4ae3668d01"
down_revision: Union[str, Sequence[str], None] = "78b6df983ffe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_contexts",
        sa.Column("service_relationships", sa.JSON(), nullable=True),
    )
    op.add_column(
        "conversation_contexts",
        sa.Column("related_services_suggested", sa.JSON(), nullable=True),
    )
    op.add_column(
        "conversation_contexts",
        sa.Column("service_transitions", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation_contexts", "service_transitions")
    op.drop_column("conversation_contexts", "related_services_suggested")
    op.drop_column("conversation_contexts", "service_relationships")
    # ### end Alembic commands ###
