"""Initial migration

Revision ID: 2ff8e51c0c13
Revises: 3d4fae13765e
Create Date: 2025-11-08 13:26:14.530475

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2ff8e51c0c13"
down_revision: str | Sequence[str] | None = "3d4fae13765e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
