"""Initial migration

Revision ID: 3d4fae13765e
Revises: 4bcacd6d5657
Create Date: 2025-11-08 13:20:14.212449

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "3d4fae13765e"
down_revision: Union[str, Sequence[str], None] = "4bcacd6d5657"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
