"""Update datetime handling to use timezone-aware datetimes

Revision ID: 78b6df983ffe
Revises: 9b1e5eb162a3
Create Date: 2025-11-08 14:06:31.578141

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "78b6df983ffe"
down_revision: Union[str, Sequence[str], None] = "9b1e5eb162a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
