"""Initial migration

Revision ID: 9b1e5eb162a3
Revises: 2ff8e51c0c13
Create Date: 2025-11-08 13:38:29.665439

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "9b1e5eb162a3"
down_revision: Union[str, Sequence[str], None] = "2ff8e51c0c13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
